# Generated by Django 6.0 on 2025-12-31 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_module_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
