# Generated by Django 6.0 on 2026-01-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name_plural': 'Lesson Progress'},
        ),
    ]
