# Generated by Django 6.0 on 2026-01-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_option_order_per_question'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='unique_question_order_per_quiz'),
        ),
    ]
