# Generated by Django 6.0 on 2026-01-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_marks',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
