# Generated by Django 6.0 on 2026-01-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_initial'),
        ('quizzes', '0002_alter_quiz_options_alter_quiz_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lessons.lesson'),
        ),
    ]
