# Generated by Django 6.0 on 2026-01-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
