# Generated by Django 6.0 on 2026-01-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('locked', 'Locked')], default='draft', max_length=20),
        ),
    ]
